author: Minor Gordon
branding:
  icon: loader
description: Generate a static site using Paradicms.
inputs:
  cache_directory_path:
    default: .paradicms/.cache
    description: Path to a directory in which to store cached data
    required: false
  data_paths:
    default: .paradicms/data
    description: colon-separated paths to one or more data files created by ETL actions,
      or directories containing data files
    required: false
  debug:
    description: Debug the action
    required: false
  pipeline_id:
    description: Pipeline id. Defaults to the name of the repository.
    required: false
  site_directory_path:
    default: _site
    description: Path to a directory where the generated static assets (CSS, HTML,
      JavaScript) should be placed
    required: false
name: Generate a static site using Paradicms.
runs:
  image: Dockerfile
  using: docker
